function F(a,f,d){function l(){0!=I&&(J=(new Date).getTime()-I)}function k(b){G=G|b;z.narme=G}function u(b){q.a("l2("+b+")");E=E|b;T()?(l(),I=0):0==I&&(I=(new Date).getTime());z.narm=E;q.a("l2e")}function r(b){K=K|b;z.naral=K}var q=new O,g=d&&d.dvObj||window.$dv,m=d&&d.impressionId||window.$uid,w=window.lg||f,h=Array(w.vb),c=w.kb/w.kc+1,b=null,e="",p={},n=0,x=Array(w.vb),t={$:{M:null,N:null,C:null,B:null,kf:!1},f:{A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,kf:!1},za:{Mb:null,Lb:null},
Rb:0},v={},A={},B,C,y={},M={},P=6,Q=!1;this.Yf=function(b){P=b};for(f=0;f<w.vb;f++)x[f]="b"+f;var D={};d&&g&&g.CommonData&&(D.ctx=d.xb,D.cmp=d.wb,D.btreg=d.btreg,D.btadsrv=d.ab,D.uid=d.Bb,D.brid=g.CommonData.BrowserId,D.brver=g.CommonData.BrowserVersion,D.tstype=g.CommonData.Scenario);D.jsver=a?a:null;var z={},H={},I=0,J="",L="",K=0,E=0,G=0,N=0;this.hd=function(){return I};this.Nd=function(b){N=N|b;z.vct=N};this.Md=function(e){b=e;H.strp=b;this.Md=function(){}};this.pc=function(){return(new Date).getTime()};
var U=this.pc();this.af=function(){return U};this.Mf=function(){E=E&-3;G=G&-2;G&=-3};this.Ob=function(){u(2)};this.Xf=function(){k(8);this.Hc()};this.Hc=function(){u(4)};this.Id=function(){r(8);this.Ob()};this.Sd=function(b){r(16);z.dbg9=b};this.Td=function(){r(1)};this.Vf=function(){this.Ob();k(1)};this.Uf=function(){this.Ob();k(2)};this.nb=function(b,e){u(8);L=q.Te(b,e)};this.Rf=function(){q.a("l1");E=E&-3;u(1);q.a("l1e")};this.Ld=function(){u(16)};this.Me=function(){return h};this.Jd=function(b,
e){m=m||d&&d.impressionId||window.$uid;q.a("ie15");if(0<=b.g){var p=Math.floor(b.g/w.kc);0<b.g%w.kc?p++:0<b.g&&p++;isNaN(h[p])&&(h[p]=0);h[p]+=e;b.H&&p>=c||0==b.H&&6<=p?n+=e:timeStampTotalBuckets=n=0}q.a("ie15e")};this.Tf=function(b){var e=b.qd;null!=b.qd&&(v.advisonl=e);null!=b.pd&&(v.adabvvponl=b.pd);z.dbg8="CSS1Compat"===document.compatMode?1:0;q.a("ff52");void 0!=document.documentMode&&null!=document.documentMode&&(z.dbg10=document.documentMode);q.a("ff52e")};this.mb=function(b){q.a("ie14");null!=
b&&(M.adbtftopg=b)};this.Sf=function(b){null!=b&&(t=b)};this.Kd=function(b){q.a("ie19");this.Sf(b.u);this.$f();q.a("ie19e")};this.Wd=function(){null!=t.$.M&&(y.vptoscrx=Math.round(t.$.M));null!=t.$.N&&(y.vptoscry=Math.round(t.$.N));null!=t.$.C&&(y.vpwdth=Math.round(t.$.C));null!=t.$.B&&(y.vphgt=Math.round(t.$.B));null!=t.f.A&&(y.adtovpx=Math.round(t.f.A));null!=t.f.v&&(y.adtovpy=Math.round(t.f.v));null!=t.f.K&&(y.adtopgx=Math.round(t.f.K));null!=t.f.L&&(y.adtopgy=Math.round(t.f.L));null!=t.f.D&&(y.adtoscrx=
Math.round(t.f.D));null!=t.f.F&&(y.adtoscry=Math.round(t.f.F));null!=t.za.Mb&&(y.scrwdth=Math.round(t.za.Mb));null!=t.za.Lb&&(y.scrhgt=Math.round(t.za.Lb));y.almesind=t.Rb};this.Xd=function(){if(B&&C){var b=t.f.o,e=t.f.j;B*C<b*e&&(A.dvp_adwdth=Math.round(B),A.dvp_adhgt=Math.round(C),!Q&&(1>=B||1>=C)&&1<b&&1<e&&($dv.registerEventCall(m,{adwdth:Math.round(b),adhgt:Math.round(e)}),Q=!0),B=b,C=e)}else B=null!=t.f.o?t.f.o:null,C=null!=t.f.j?t.f.j:null;null!=B&&(A.adwdth=Math.round(B));null!=C&&(A.adhgt=
Math.round(C))};this.$f=function(){l();for(var b=0;b<h.length;b++)h[b]&&(p[x[b]]=h[b]);this.Wd();this.Xd();q.G(y,v);q.G(y,A);q.G(y,M)};this.fd=function(){return 1E3<=n};this.Xe=function(b){var c={};m=m||d&&d.impressionId||window.$uid;var n=-1,h=q.Ue();try{g&&g.tags[m]&&g.tags[m].getTimeDiff&&(n=g.tags[m].getTimeDiff())}catch(a){}var x=[];q.G(c,D);switch(b){case 1:e=n;q.G(c,H);q.G(c,z);c.napt=J;q.G(c,y);c.dvp_log=h;c.napr=L;c.ismms=e;c.isumms=n;break;case 2:q.G(c,H);q.G(c,z);c.napt=J;q.G(c,y);c.dvp_log=
h;c.napr=L;c.isnmms=n;break;case 3:c.istoms=n;case 4:case 8:q.G(c,H);q.G(c,M);q.G(c,A);c.isbxdms=n;q.G(c,p);c.nvr=P;break;case 5:q.G(c,H);q.G(c,M);q.G(c,A);q.G(c,v);c.ismms=e||n;c.isiabvms=n;c.isuiabvms=n;break;case 16:q.G(c,H);q.G(c,z);c.napt=J;c.dvp_log=h;c.napr=L;c.ishems=n;break;case 7:return x.join("");default:q.G(c,H),q.G(c,p),q.G(c,z),q.G(c,v),c.napt=J,c.dvp_log=h,c.napr=L}c.evid=b;c.ctime=this.pc();return c};this.Le=function(){q.a("ie17");for(var b=[],c=0;c<w.vb;c++)b[c]=h[c]?h[c]:0;return b};
var T=this.Zc=function(){return 2==(E&2)&&8!=(K&8)||4==(E&4)||8==(G&8)&&8==(K&8)?!1:!0};this.Ff=function(b){q.a("l3");b=q.ia(b);q.a("cm3e");b&&(z.dbg5=b.w,z.dbg6=b.h);q.a("l3e")};return this}function R(a,f){var d=new O,l=a&&a.impressionId||window.$uid,k=0;this.ga=function(a,r){if(f){var q=f.Xe(a);r&&d.G(q,r);4==a||8==a?(5>k&&this.Fc(l,q,!0),k++):this.Fc(l,q,!1)}};this.Fc=function(a,f,d){$dv&&$dv.registerEventCall&&a&&$dv.registerEventCall(a,f,null,!d,d)}}
function S(){this.ga=function(){};this.Fc=function(){}}
function V(a,f,d,l){function k(){if(1==t){try{for(var b in n)x.removeChild(n[b]);e.document.body.removeChild(x)}catch(c){}t=!1}}function u(b){b=b||0;var c=g(0);c.td()?7<c.Ab()?(k(),A=v=t=!1):(t=!0,v=!1):20>b?(b++,setTimeout(u,50,b)):(t=v=A=!1,k())}function r(b){$dv&&$dv.tags&&$dv.tags[l]&&$dv.tags[l].getTimeDiff&&$dv.tags[l].getTimeDiff();if(null!==b.tb)for(var c=0;c<b.tb.length;c++){var e=g(c).Ab();0==c?e>B&&(B=e):e>C&&(C=e)}}function q(b){for(var c=!0,e=0;13>=e;e++)var p=g(e),c=c&(null!==p&&p.td());
if(!c)return null;b.Y={ob:!1,pb:!1,Za:!1,$a:!1};b.Wc=0;b.Sa=0;b.Dc=0;b.vc=0;b.Aa=0;b.tb=Array(13);c=g(0).Ab();for(e=1;13>=e;e++)if(p=5<Math.abs(g(e).Ab()-c),b.tb[e]=p)switch(b.Wc++,e){case 2:b.Y.ob=!0;b.Sa++;break;case 3:b.Y.pb=!0;b.Sa++;break;case 4:b.Y.Za=!0;b.Sa++;break;case 5:b.Y.$a=!0;b.Sa++;break;case 6:case 7:case 8:case 9:b.Dc++;break;case 10:case 11:case 12:case 13:b.vc++}if(13===b.Wc)return b.Aa=100,r(b),!0;c=b.tb;if(!1===c[1]){if(3<=b.vc||3<=b.Dc||3<=b.Sa)return r(b),null;b.Aa=0;r(b);return!1}if(!0===
c[1]&&(!0===c[2]&&!0===c[3]||!0===c[2]&&!0===c[4]||!0===c[3]&&!0===c[5]||!0===c[4]&&!0===c[5])||!0===c[1]&&4==b.Dc||!0===c[1]&&4==b.vc&&1<=b.Sa)return b.Aa=50,r(b),!0;if(c[2]&&c[5]&&!(c[6]&&c[10]&&c[1]&&c[13]&&c[9])||c[4]&&c[3]&&!(c[8]&&c[12]&&c[1]&&c[11]&&c[7]))return r(b),null;b.Aa=0;r(b);return!1}function g(b){b=n[b];var c=null;b&&(c=b.contentWindow);return c}function m(){for(var b=p.getBoundingClientRect(),e=b.width,a=b.height,x=e/(1+h),w=a/(1+h),g=e/h,f=a/h,d=0;13>=d;d++){var v=b.left,t=b.top;
switch(d){case 0:t=v=-1E5;break;case 1:v+=(e-c)/2;t+=(a-c)/2;break;case 3:v+=e-c;break;case 4:t+=a-c;break;case 5:v+=e-c;t+=a-c;break;case 6:v+=(e-g)/2;t+=(a-f)/2;break;case 7:v+=(e-g)/2+g;t+=(a-f)/2;break;case 8:v+=(e-g)/2;t+=(a-f)/2+f;break;case 9:v+=(e-g)/2+g;t+=(a-f)/2+f;break;case 10:v+=(e-x)/2;t+=(a-w)/2;break;case 11:v+=(e-x)/2+x;t+=(a-w)/2;break;case 12:v+=(e-x)/2;t+=(a-w)/2+w;break;case 13:v+=(e-x)/2+x,t+=(a-w)/2+w}6<=d&&(v-=c/2,t-=c/2);var k=n[d];k.style.left=v+"px";k.style.top=t+"px"}}
function w(){if(null!=p&&null!=p.parentNode){v=!0;x=e.document.createElement("div");e.document.body.appendChild(x);for(var b=0;13>=b;b++){var a=e.document.createElement("iframe");a.width=c;a.height=c;a.style.position="absolute";a.frameBorder="0";a.style.visibility="hidden";a.style.zIndex=-9999999;a.style.display="block";a.src="javascript:no=false;yes=true;("+function(){window.xf={te:100};window.dd=no;window.sb=0;window.od=0;window.wd=0;window.og=no;window.Ab=function(){return window.wd};window.td=
function(){return window.dd};window.rf=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame;window.cc=function(){window.sb++;window.rf(window.cc,document)};window.cc();setInterval(function(){10>window.sb&&window.cc();window.wd=window.sb-window.od;window.od=window.sb},window.xf.te);window.setTimeout(function(){window.dd=yes},250)}.toString()+")();";x.appendChild(a);n.push(a)}m()}}var h=Math.sqrt(2),c=1,b=new O,e=null,p=null,
n=[],x,t=!1,v=!1,A=b.Gb(a,f,d);0==b.Da()&&(c=8);var B=0,C=0;this.ff=function(){0==v&&(0==(this.Ea()&&(null!=p&&b.sd(p,e)?!0:!1))?t=!1:(w(),u()))};this.Ea=function(){return A};this.Cc=function(){return t};this.Ta=function(b,c){e=b;p=c;this.ff()};this.ib=function(){if(0==t)return null;var b={};return null==q(b)?null:b}}
function W(a,f,d){function l(){var a=q.getClientRects()[0];if(!m||!a||m.left!==a.left||m.right!==a.right||m.top!==a.top||m.bottom!==a.bottom){m=a;for(var h=a.right-a.left,c=a.bottom-a.top,b=h/(1+u),e=c/(1+u),p=h/u,n=c/u,x=0;13>=x;x++){var g=Math.round(5*Math.random()),f=a.left+r.document.body.scrollLeft,d=a.top+r.document.body.scrollTop;switch(x){case 0:d=f=-1E5;break;case 1:f+=(h-1)/2+g;d+=(c-1)/2+g;break;case 2:f+=g;d+=g;break;case 3:d+=g;f+=h-1-g;break;case 4:f+=g;d+=c-1-g;break;case 5:f+=h-1-
g;d+=c-1-g;break;case 6:f+=(h-p)/2+g;d+=(c-n)/2+g;break;case 7:f+=(h-p)/2+p-g;d+=(c-n)/2+g;break;case 8:f+=(h-p)/2+g;d+=(c-n)/2+n-g;break;case 9:f+=(h-p)/2+p-g;d+=(c-n)/2+n-g;break;case 10:f+=(h-b)/2+g;d+=(c-e)/2+g;break;case 11:f+=(h-b)/2+b-g;d+=(c-e)/2+g;break;case 12:f+=(h-b)/2+g;d+=(c-e)/2+e-g;break;case 13:f+=(h-b)/2+b-g,d+=(c-e)/2+e-g}6<=x&&(f-=.5,d-=.5);f=Math.round(f);d=Math.round(d);g=r.document.getElementById("OVVBeaconContainer_"+x);g.style.left=f+"px";g.style.top=d+"px"}}}function k(){if("https://cdn.zentrick.com/openvv/2.5.4/OVVBeacon.swf"!=
"LRU_FWS_NOCAEB".split("").reverse().join("")){for(var a=0;13>=a;a++){var h=r.document.createElement("DIV");h.id="OVVBeaconContainer_"+a;h.style.position="absolute";h.style.zIndex=-99999;h.innerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="1" height="1"><param name="movie" value="https://cdn.zentrick.com/openvv/2.5.4/OVVBeacon.swf" /><param name="quality" value="low" /><param name="flashvars" value="id='+a+"&index="+a+'" /><param name="bgcolor" value="#ffffff" /><param name="wmode" value="transparent" /><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="false" />\x3c!--[if !IE]>--\x3e<object id="OVVBeacon_'+
a+'" type="application/x-shockwave-flash" data="https://cdn.zentrick.com/openvv/2.5.4/OVVBeacon.swf" width="1" height="1"><param name="quality" value="low" /><param name="flashvars" value="id='+a+"&index="+a+'" /><param name="bgcolor" value="#ff0000" /><param name="wmode" value="transparent" /><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="false" />\x3c!--<![endif]--\x3e</object>';r.document.body.insertBefore(h,r.document.body.firstChild)}l.bind(this)();setInterval(l.bind(this),
500)}}var u=Math.sqrt(2),r,q,g=new O,m;this.zc=function(){return g.Ac(a,f,d)};this.Ta=function(a,h){r=a;q=h;k()};this.ib=function(){var a;a:{for(var h=a=0,c=0,b=0,e=Array(13),p=0;13>=p;p++)if(0!==p){var n=r.document.getElementById("OVVBeacon_"+p);if(!n.isViewable){a=null;break a}n=n.isViewable();if(e[p]=n)switch(a++,p){case 2:case 3:case 4:case 5:h++;break;case 6:case 7:case 8:case 9:c++;break;case 10:case 11:case 12:case 13:b++}}a=13===a?100:!1===e[1]?3<=b||3<=c||3<=h?null:0:!0===e[1]&&(!0===e[2]&&
!0===e[3]||!0===e[2]&&!0===e[4]||!0===e[3]&&!0===e[5]||!0===e[4]&&!0===e[5])||!0===e[1]&&4==c?50:e[2]&&e[5]&&!(e[6]&&e[10]&&e[1]&&e[13]&&e[9])||e[4]&&e[3]&&!(e[8]&&e[12]&&e[1]&&e[11]&&e[7])?null:0}return a}}
function X(a,f,d,l,k,u,r,q){this.b=new O;this.window=a;this.c=f;this.V=d;this.O=l;this.da=r&&r.Enums.BrowserId||window.$dv.Enums.BrowserId;this.fa=r&&r.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario;this.P=k;this.uc=u;this.wa=this.S=null;this.nd=this.window?this.b.Hb(this.window.top):this.b.Hb(window.top);this.jf=this.V!=this.fa.CrossDomain&&this.b.cb("ofs")&&this.nd;this.S=new V(this.V,this.O,r,q);null!=this.S&&this.S.Ea()&&this.S.Ta(this.window,this.c);this.wa=new W(this.V,this.O,r);null!=
this.wa&&this.wa.zc()&&this.wa.Ta(this.window,this.c);this.Db=this.Ib=this.sa=null;this.jb=!1;var g=0;this.ka={he:1,ie:2,ce:4,Wb:8,be:16,Xb:32,ge:64};this.Gc=function(a,h,c,b){if(b&&b.insertBefore&&b.firstChild&&(a=this.window.document.createElement(a))){for(var e in h)a[e]=h[e];for(e in c)a.style[e]=c[e];b.insertBefore(a,b.firstChild);return a}return null};this.Je=function(a,h,c){var b=this.window.top,e=a.width,p=a.height;0>c.left?(e=a.width-Math.abs(c.left),0>h.Ga&&(e-=Math.abs(h.Ga))):0>h.Ga&&
(e=a.width-Math.abs(h.Ga)+c.left,e=e>a.width?a.width:e);var n=a.width,x=Math.min(this.b.Ca(b.window).clientWidth,b.innerWidth),g=screen.availWidth-x-h.Ga,f=0;e<n?(n=e,f=x-e,0>h.Ga&&(f-=Math.abs(h.Ga))):f=x-n-c.left;0>f?(e=n-Math.abs(f),0>g&&(e-=Math.abs(g))):0>g&&(e=n-Math.abs(g)+f,e=e>n?n:e);h=screen.availHeight-h.Nf-b.outerHeight;b=Math.min(this.b.Ca(b.window).clientHeight,b.innerHeight)-a.height-c.top;0>b?(p=a.height-Math.abs(b),0>h&&(p-=Math.abs(h))):0>h&&(p=a.height-Math.abs(h)+b,p=p>a.height?
a.height:p);0>c.top&&(p-=Math.abs(c.top));return{dg:e,eg:p}};this.oc=function(a,h,c,b){var e=c.C,p=c.B,n=0;c=0;var g={width:h.right-h.left,height:h.bottom-h.top};if(0>h.bottom||0>h.right||h.top>p||h.left>e||0>=g.width||0>=g.height)return 0;0>h.top?Math.abs(h.top)>=g.height?n=0:(n=g.height+h.top,n>p&&(n=p)):n=h.top+g.height>p?p-h.top:g.height;0>h.left?Math.abs(h.left)>=g.width?c=g.width:(c=g.width+h.left,c>e&&(c=e)):c=h.left+g.width>e?e-h.left:g.width;this.jf&&(a=this.Je(g,a,h),c=a.dg,n=a.eg);return 0>=
c||0>=n?0:Math.round(c*n/(g.width*g.height)*(b?g.width*g.height/((b.right-b.left)*(b.bottom-b.top)):1)*100)};this.jd=function(a,h){var c=h.C,b=h.B,e={ob:!0,pb:!0,Za:!0,$a:!0};try{if(0>a.top||a.top>b)e.pb=!1,e.ob=!1;if(0>a.bottom||a.bottom>b)e.$a=!1,e.Za=!1;if(0>a.left||a.left>c)e.ob=!1,e.Za=!1;if(0>a.right||a.right>c)e.pb=!1,e.$a=!1}catch(p){}return e};this.nc=function(a,h){try{var c={x:a.offsetLeft,y:a.offsetTop},b;a.offsetParent?(b=this.nc(a.offsetParent,h),c.x+=b.x,c.y+=b.y):h!=h.parent&&this.b.Yb(h,
h.parent)&&(b=this.nc(h.frameElement,h.parent),c.x+=b.x,c.y+=b.y);return c}catch(e){return{x:null,y:null}}};var m=this.b.Fb();this.qa=function(a){if(this.V==this.fa.CrossDomain)if(this.b.ya(this.window)&&this.window.$sf.ext.geom)this.qa=function(){var b=this.b.Qa(this.window),c=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(b.win.h):this.P.Explorer.ca,e={C:null,B:null,M:null,N:null,s:!1};e.C=parseInt(b.win.w);e.B=parseInt(b.win.h);e.M=parseInt(b.win.l);
e.N=parseInt(b.win.t)+c;e.s=!0;return e};else if(this.O.U==this.da.Firefox)this.qa=function(){var b=8==screen.top-this.window.screenY&&8==screen.left-this.window.screenX,c=b?0:this.window.screenX-screen.left,b=b?0:this.window.screenY-screen.top,e={C:null,B:null,M:null,N:null,s:!1};e.C=this.window.outerWidth;e.B=this.window.outerHeight-this.P.Firefox.ca;e.M=c;e.N=b+this.P.Firefox.ca;e.s=!0;return e};else if(this.b.xc(this.window)){var h=this;this.window.context.observeIntersection(function(b){b.forEach(function(b){h.sa=
b})});this.qa=function(){var b={C:null,B:null,s:!1,M:null,N:null};null!=this.sa?(b.C=this.sa.rootBounds.width,b.B=this.sa.rootBounds.height):(b.C=0,b.B=0);b.s=!0;return b}}else if(this.O.U==this.da.IE&&10<=parseInt(this.O.pa))m&&this.Kb(),this.qa=function(){var b=-8==this.window.screenY&&-8==this.window.screenX,c=b?0:this.window.screenX,b=b?0:this.window.screenY,e={C:null,B:null,M:null,N:null,s:!1};e.C=this.window.outerWidth;e.B=this.window.outerHeight-this.P.Explorer.ca;e.M=c;e.N=b+this.P.Explorer.ca;
m?(this.jb||this.Kb(),e.s=!1):e.s=!0;return e};else if(this.O.U==this.da.IE&&/[6-9]|[10]/.test(this.O.pa)){var c=this.Gc("iframe",{name:"dv_ie9onload",src:"",width:0,height:0,Ee:0,sf:"0",tf:"0"},{display:"inline",position:"absolute",top:0,left:0,cg:"none",zIndex:0,border:0},this.window.document.body),b=this.Gc("iframe",{name:"dv_ie9onmousemove",src:"",width:0,height:0,Ee:0,sf:"0",tf:"0"},{display:"inline",position:"absolute",top:0,left:0,cg:"none",zIndex:0,border:0},this.window.document.body),e=b.contentWindow||
b.window||b.contentDocument.window||b.contentWindow.window||this.window.gg,p=c.contentDocument||c.contentWindow.document,c=b.contentDocument||b.contentWindow.document,n="<html><head><script >window.onload = "+function(b){b&&(window.event=b);isFinite(String(window.event.clientY))&&(parent.bb={$b:window.event.clientY,Zb:window.event.clientX,Vd:window.event.screenY-window.event.clientY-window.screenY})}.toString()+"; \x3c/script></head><body></body></html>",b='<html><head></head><body><script > function runMoM(){ window.document.body.fireEvent("onmousemove");} window.document.body.onmousemove = '+
function(b){b&&(window.event=b);isFinite(String(window.event.clientY))&&(parent.ta={$b:window.event.clientY,Zb:window.event.clientX,La:window.event.screenY-window.event.y,Ka:window.event.screenX-window.event.x})}.toString()+"; runMoM();\x3c/script></body></html>";c.open("text/html","replace");c.write(b);c.close();p.open("text/html","replace");p.write(n);p.close();("CSS1Compat"===document.compatMode?this.window.document.documentElement:this.window.document.body).clientLeft;this.qa=function(){e.runMoM();
p.open("text/html","replace");p.write(n);p.close();var b=this.window.ta,c=this.window.bb,a=screen.availWidth,h=screen.availHeight,c=c?c.Vd:this.P.Explorer.ca;if(b){var g=b.Ka,f=b.La;b.Ka>=a&&(b.Ka-=a);b.La>=h&&(b.La-=h);var d={C:null,B:null,M:null,N:null,s:!1};d.C=this.window.outerWidth?this.window.outerWidth-20:a-b.Ka-20;d.B=this.window.outerHeight?this.window.outerHeight-c-10:h-b.La-10;d.M=g;d.N=f;d.s=!0}else d={C:null,B:null,M:null,N:null,s:!1},d.C=this.window.outerWidth?this.window.outerWidth-
20:a-20,d.B=this.window.outerHeight?this.window.outerHeight-c-10:h-10,d.M=null,d.N=null,d.s=!1;return d}}else this.b.Fb()?(this.Kb(),this.qa=function(){this.jb||this.Kb();var b={C:null,B:null,M:null,N:null,s:!1};b.C=this.window.outerWidth;b.B=this.window.outerHeight-this.P.Chrome.ca;b.s=!1;return b}):this.qa=this.O.U==this.da.Chrome?function(){var b={C:null,B:null,M:null,N:null,s:!1},c=!1;try{b.C=this.window.frameElement.offsetParent.parentNode.clientWidth,b.B=this.window.frameElement.offsetParent.parentNode.clientHeight,
c=!0}catch(e){}b.M=this.window.screenX;b.N=this.window.screenY;b.s=c;return b}:null!=this.S&&this.S.Ea()?function(){var b={C:null,B:null,M:null,N:null,s:!1};b.C=this.window.outerWidth;b.B=this.window.outerHeight-this.P.Safari.ca;b.s=!1;return b}:function(){return{C:null,B:null,M:null,N:null,s:!1}};else this.qa=function(){var b,c,e=this.window.top;void 0!=e.mozInnerScreenX&&null!=e.mozInnerScreenX?(b=e.mozInnerScreenX,c=e.mozInnerScreenY):void 0!=e.screenX&&null!=e.screenX?0!=e.screenLeft+8&&e.screenLeft+
8!=screen.width||0!=e.screenTop+8&&e.screenTop+8!=screen.height?(b=e.screenLeft,c=e.screenTop+(e.outerHeight-e.innerHeight)):(b=e.screenLeft+8,c=e.screenTop+(e.outerHeight-e.innerHeight)+8):(b=e.screenLeft,c=e.screenTop);var a={C:null,B:null,M:null,N:null,s:!1},p=this.b.Ca(e);a.C=e.innerWidth||p.clientWidth;a.B=e.innerHeight||p.clientHeight;a.M=b;a.N=c;a.s=!0;return a};return this.qa(a)};this.ma=function(a,h){g=1;this.V==this.fa.CrossDomain?this.b.ya(this.window)&&this.window.$sf.ext.geom&&this.b.Qa(this.window).par?
(g=8,this.ma=function(){var c=this.b.Qa(this.window),b=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(c.win.h):this.P.Explorer.ca,e={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null};e.A=parseInt(c.self.l)-parseInt(c.par.l);e.v=parseInt(c.self.t)-parseInt(c.par.t);e.K=parseInt(c.self.l);e.L=parseInt(c.self.t);e.D=parseInt(c.win.l)+e.A;e.F=parseInt(c.win.t)+e.v+b;e.o=parseInt(c.self.w);e.j=parseInt(c.self.h);
e.s=!0;e.rect={top:e.v,bottom:e.v+e.j,left:e.A,right:e.A+e.o};return e}):this.O.U==this.da.Firefox?this.ma=function(){var c=1;window.devicePixelRatio&&(c=window.devicePixelRatio);var b=this.window.screenX,e=this.window.screenY,a=this.window.mozInnerScreenX/c-b,c=this.window.mozInnerScreenY/c-e-this.P.Firefox.ca,a={left:a,top:c,right:a+this.window.innerWidth,bottom:c+this.window.innerHeight},c={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null};c.A=a.left;c.v=a.top;
c.K=null;c.L=null;c.D=b+a.left;c.F=e+a.top;c.o=this.window.innerWidth;c.j=this.window.innerHeight;c.s=!0;c.rect=a;this.b.Qb()&&(c=this.zb(c));return c}:this.b.xc(this.window)?(g=32,this.ma=function(){var c={A:null,v:null,o:null,j:null,s:!1,rect:null,R:null,na:null,K:null,L:null,D:null,F:null};null!=this.sa?(c.A=this.sa.boundingClientRect.left,c.v=this.sa.boundingClientRect.top,c.o=this.sa.boundingClientRect.width,c.j=this.sa.boundingClientRect.height):(c.A=0,c.v=0,c.o=0,c.j=0);c.s=!0;c.rect={top:c.v,
bottom:c.v+c.j,left:c.A,right:c.A+c.o};return c}):null!=this.wa&&this.wa.zc()?this.ma=function(){var c={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null};null!=this.c&&(adData=this.b.eb(this.c),c.o=adData?adData.w:this.window.innerWidth,c.j=adData?adData.h:this.window.innerHeight);return c}:this.O.U==this.da.IE&&10<=parseInt(this.O.pa)?this.ma=function(c){var b=this.window.screenLeft-window.screenX,e=this.window.screenTop-window.screenY-this.P.Explorer.ca,b={left:b,
top:e,right:b+this.window.innerWidth,bottom:e+this.window.innerHeight},e={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null};e.A=b.left;e.v=b.top;e.K=null;e.L=null;e.D=c.M+b.left;e.F=c.N+b.top;e.o=this.window.innerWidth;e.j=this.window.innerHeight;e.s=!m;e.rect=b;this.b.Qb()&&(e=this.zb(e));return e}:this.O.U==this.da.IE&&/[6-9]|[10]/.test(this.O.pa)?this.ma=function(){if(8==document.documentMode)return{A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,
rect:null,R:null,na:null};var c=this.window.bb&&this.window.ta?this.window.bb.$b-this.window.ta.$b:0,b=this.window.bb&&this.window.ta?this.window.bb.Zb-this.window.ta.Zb:0,e=this.b.Ca(this.window),a={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null};a.A=b;a.v=c;a.K=null;a.L=null;a.D=this.window.ta?b+this.window.ta.Ka:null;a.F=this.window.ta?c+this.window.ta.La:null;a.o=this.window.innerWidth||e.clientWidth;a.j=this.window.innerHeight||e.clientHeight;a.s=!0;a.rect=
{left:b,top:c,right:b+(this.window.innerWidth||e.clientWidth),bottom:c+(this.window.innerHeight||e.clientHeight)};this.b.Qb()&&(a=this.zb(a));return a}:this.b.Fb()?(g=512,this.ma=function(){var c={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null};null!=this.c&&(adData=this.b.eb(this.c),c.o=adData?adData.w:this.window.innerWidth,c.j=adData?adData.h:this.window.innerHeight);return c}):this.ma=this.O.U==this.da.Chrome?function(){var c=null,b=null,e=!1;try{var a=this.window.frameElement.offsetTop,
c=this.window.frameElement.offsetLeft-this.window.frameElement.offsetParent.scrollLeft,b=a-this.window.frameElement.offsetParent.scrollTop,e=!0}catch(n){}a={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null};a.A=c;a.v=b;a.K=null;a.L=null;a.D=null;a.F=null;a.o=this.window.innerWidth;a.j=this.window.innerHeight;a.s=e;a.rect=e?{left:c,top:b,right:c+this.window.innerWidth,bottom:b+this.window.innerHeight}:null;this.b.Qb()&&(a=this.zb(a));return a}:null!=this.S&&this.S.Ea()?
function(){var c={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null};null!=this.c&&(adData=this.b.eb(this.c),c.o=adData?adData.w:this.window.innerWidth,c.j=adData?adData.h:this.window.innerHeight);return c}:function(){return{A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null}}:this.ma=function(c){var b=this.nc(this.c,this.window),e={A:null,v:null,K:null,L:null,D:null,F:null,o:null,j:null,s:!1,rect:null,R:null,na:null},a=this.b.qc(this.c,
this.window),n=this.b.Mc(this.c,this.window);e.A=n.left;e.v=n.top;e.K=b.x;e.L=b.y;e.D=c.M+n.left;e.F=c.N+n.top;e.o=n.w;e.j=n.h;e.s=!0;e.rect=a;e.R=n;return e};return this.ma(a,h)};this.zb=function(a){if(this.window.document.body==this.c||this.window.document.documentElement==this.c)return a;var h=this.b.eb(this.c);if(h){var c=h.w,b=h.h,e=a.A,p=a.v,n=a.F,g=a.D;null!=a.A&&null!=a.v&&null!=a.j&&null!=a.o&&a.rect&&(0<h.t?(p=a.v+h.t,null!=a.F&&(n=a.F+h.t)):b+=h.t,0<h.l?(e+=h.l,null!=a.D&&(g=a.D+h.l)):
c+=h.l,h.r>a.o&&(c-=h.r-a.o),h.Vc>a.j&&(b-=h.Vc-a.j),a.o=0<c?c:0,a.j=0<b?b:0,a.A=e,a.v=p,a.F=n,a.D=g,a.rect.left=a.A,a.rect.top=a.v,a.rect.right=a.A+h.w,a.rect.bottom=a.v+h.h,a.R={w:c,h:b,left:e,right:e+c,top:p,bottom:p+b})}return a};this.$e=function(){var a=screen.availWidth,h=screen.availHeight,c=screen.width,b=screen.height,e=0,p=0;this.nd&&(p=this.window.top,e=p.screenX,p=p.screenY);return{s:this.P.Da?!1:"undefined"!==typeof e,Mb:a||c,Lb:h||b,mg:e,ng:p,Ga:e-(c-a),Nf:p-(b-h)}};this.He=function(){var a=
this.$e(),h=this.qa(a),c=this.ma(h,a);return{$:h,f:c,za:a,Rb:(null==h.M||null==h.N?0:this.ka.he)|(null==h.C||null==h.B?0:this.ka.ie)|(null==c.A||null==c.v?0:this.ka.ce)|(null==c.K||null==c.L?0:this.ka.Wb)|(null==c.D||null==c.F?0:this.ka.be)|(null==c.j||null==c.o?0:this.ka.Xb)|(null==a.Lb||null==a.Mb?0:this.ka.ge),H:this.ad(c.j,c.o)}};this.ad=function(a,h){null==a&&(a=0);null==h&&(h=0);return 1!=this.P.Da?242500<=a*h:!1};this.Qe=function(){this.b.a("c10");if(null!=this.c)if(this.b.sd(this.c,this.window))try{var a=
{timeStamp:new Date,g:-3,W:-3,u:null,H:!1,aa:0};if(!this.uc())return a;var h=this.He(),c,b=h.f,e=h.$;c=b&&b.o&&b.j&&e&&e.C&&e.B?b.o>e.C||b.j>e.B:!1;var p;if(!h.f.s||!h.$.s){if(this.b.ya(this.window)&&this.window.$sf.ext.inViewPercentage){p=this.window.$sf.ext.inViewPercentage();if(this.P.Da&&c&&this.S.Ea()){var n={timeStamp:new Date,g:-3,W:-3,u:null,H:!1,aa:2};if(0==this.S.Cc())n.g=-6,n.W=-6,this.S.Ta(this.window,this.c);else{var d=this.S.ib();if(null!=d)var f=d.Y}}return{timeStamp:new Date,g:p,W:p,
u:h,H:h.H,aa:16,Ma:c,Y:f}}if(m&&this.jb){p=0;null!=this.Db&&(p=Math.round(100*this.Db.intersectionRatio));var k=this.ad(h.f.j,h.f.o);this.P.Da&&c&&this.S.Ea()&&(n={timeStamp:new Date,g:-3,W:-3,u:null,H:!1,aa:2},0==this.S.Cc()?(n.g=-6,n.W=-6,this.S.Ta(this.window,this.c)):(d=this.S.ib(),null!=d&&(f=d.Y)));return{timeStamp:new Date,g:p,W:p,u:h,H:k,Ma:c,aa:512,Y:f}}if(this.wa.zc()){var l={timeStamp:new Date,g:-3,W:-3,u:null,H:!1,aa:64},d=this.wa.ib();null!=d&&(l.u=h,l.H=h.H,l.g=d,l.W=d,l.Ma=c);return l}if(this.S.Ea())return n=
{timeStamp:new Date,g:-3,W:-3,u:null,H:!1,aa:2},0==this.S.Cc()?(n.g=-6,n.W=-6,this.S.Ta(this.window,this.c)):(d=this.S.ib(),null!=d&&(n.u=h,n.H=h.H,n.g=d.Aa,n.W=d.Aa,n.Ma=c,n.Y=d.Y)),n;a.u=h;g&&(a.aa=g);return a}if(h.f&&h.f.R&&(0===h.f.R.w||1===h.f.R.w||0===h.f.R.h||1===h.f.R.h))return{timeStamp:new Date,g:-5,W:-5,u:h,aa:g};h.f.R?(p=this.oc(h.za,h.f.R,h.$,h.f.rect),f=this.jd(h.f.R,h.$)):(p=this.oc(h.za,h.f.rect,h.$),f=this.jd(h.f.rect,h.$));return{timeStamp:new Date,g:p,W:p,u:h,H:h.H,aa:g,Y:f,Ma:c}}catch(q){return{timeStamp:new Date,
g:-4,W:-4,u:null,H:!1,aa:g}}else return{timeStamp:new Date,g:-2,W:-2,u:null,H:!1,aa:0};else return{timeStamp:new Date,g:-1,W:-1,u:null,H:!1,aa:0}};this.Ie=function(a,h){this.b.a("c11");var c=null,b=null;if(null!=a.u){var e=a.u.f;h<=this.P.zf&&(c=0<=a.g||-5==a.g?a.H&&a.g>=this.P.kb||0==a.H&&50<=a.g?!0:!1:null,b=a.H?this.P.kb/100:.5,b=0==c?0>e.v+e.j*b?!0:!1:1==c?!1:null)}return{pd:b,qd:c}};this.Eb=function(a){this.b.a("c12");var h=null;if(2!=a.aa&&512!=a.aa&&null!=a.u){var c=a.u.Rb,b=a.u.f;(c&this.ka.Wb)==
this.ka.Wb&&(c&this.ka.Xb)==this.ka.Xb&&(h=this.oc(a.u.za,{left:b.K,top:b.L,right:b.K+b.o,bottom:b.L+b.j},a.u.$,b.rect),h=0<=a.g?a.H&&h>=this.P.kb||0==a.H&&50<=h?!1:!0:null)}this.b.a("c12e");return h};this.Kb=function(){function a(c){c.forEach(function(b){h.Db=b})}var h=this;"undefined"!=typeof IntersectionObserver&&null!=this.c&&(g=512,this.Ib=new IntersectionObserver(a,{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]}),this.Ib.observe(this.c),this.jb=!0)};this.ef=function(){this.c=null;null!=this.Ib&&
(this.Ib.disconnect(),this.Db=null,this.jb=!1)}}
function O(){this.getElementVolume_object=function(a){var f=a.getAttribute("width"),d=a.getAttribute("height");null==f||""==f||null==d||""==d?(a=a.parentNode,a={w:a.clientWidth,h:a.clientHeight}):a={w:f,h:d};return a};this.nf=function(a){var f=0;try{for(;null!=a&&10>f;){if("none"==window.getComputedStyle(a).display||"hidden"==window.getComputedStyle(a).visibility)return!1;a=a.parentElement;f++}}catch(d){}return!0};this.ia=function(a,f){this.a("cm1");var d=null,l=a.nodeName.toLowerCase();f&&this["getElementVolume_"+
l]&&(d=this["getElementVolume_"+l](a));if(!d&&(d=this.eb(a),this.a("cm2e"),!d||1>=d.w||1>=d.h))return this.a("cm1e"),{w:0,h:0};d.w.indexOf&&d.w.indexOf("px")&&(d.w=d.w.replace("px",""));d.h.indexOf&&d.h.indexOf("px")&&(d.h=d.h.replace("px",""));this.a("cm1e");return d};this.eb=function(a){this.a("cm2");try{var f;return document.body.getBoundingClientRect&&(f=a.getBoundingClientRect())?{w:f.right-f.left,h:f.bottom-f.top,l:f.left,t:f.top,Vc:f.bottom,r:f.right}:null}catch(d){return null}};this.Ca=function(a){return a.document.documentElement.clientHeight?
a.document.documentElement:a.document.body};this.gd=function(a,f){this.a("ff9");var d=0,l=!1;if(a.document.all)for(var k=0;k<a.document.all.length;k++)"BODY"==a.document.all[k].nodeName&&(l=!0),l&&("width"==f?a.document.all[k].width>d&&(d=a.document.all[k].width):a.document.all[k].height>d&&(d=a.document.all[k].height));this.a("ff9e");return d};this.vd=function(a,f){for(var d=this.Ca(a),l=a.innerWidth||d.clientWidth||this.gd(a,"width"),d=a.innerHeight||d.clientHeight||this.gd(a,"height"),k=f.length,
u=0,r=0;r<k;r++)if(15>=Math.abs(l-f[r].w)){u=f[r].h.length;for(l=0;l<u;l++)if(15>=Math.abs(d-f[r].h[l]))return!0;break}return!1};this.ag=function(a){for(var f=[],d=-1;f[++d]=a[d];);f.length--;return f};this.Tb=function(a,f,d,l,k,u,r){r=r||15;var q=a.getElementsByTagName("*"),q=this.ag(q);q.unshift(a);for(var g="EMBED IFRAME OBJECT IMG SPAN DIV SVG CANVAS".split(" "),m=[],w=0;w<q.length;w++){var h=q[w];if(-1!=g.indexOf(h.nodeName.toUpperCase())){var c=l(h);!c||k&&u&&(Math.abs(c.w-k)>r||Math.abs(c.h-
u)>r)||m.push({Uc:c.w*c.h,w:c.w,h:c.h,type:h.nodeName||"other",De:h})}}m=m.sort(function(b,c){return c.Uc-b.Uc||g.indexOf(c.type)-g.indexOf(b.type)});(f=0<m.length&&m[0].w>f&&m[0].h>d?m[0].De:null)&&a&&(f.Cb=a.Cb);return f};this.sd=function(a,f){this.a("ff10");try{if(!a)return!1;for(f||(f=window);a!=f.document&&a.parentNode;)a=a.parentNode;this.a("ff10e");return a==f.document}catch(d){return!1}};this.qc=function(a,f){var d=f.parent,l={left:0,right:0,top:0,bottom:0};if(a){var k=a.getBoundingClientRect();
f!=d&&this.Yb(f,d)&&(l=this.qc(f.frameElement,d));l={left:k.left+l.left,right:k.right+l.left,top:k.top+l.top,bottom:k.bottom+l.top}}return l};this.Yb=function(a,f){var d=!1;if(a==f)d=!0;else try{a.document.domain==f.document.domain&&(d=!0)}catch(l){}return d};this.Re=function(a){if(a)try{if(a.contentDocument&&this.rd(a.contentDocument))return a.contentDocument;if(a.contentWindow&&this.Hb(a.contentWindow))return a.contentWindow.document}catch(f){}return null};this.md=function(a){return a?a.defaultView||
a.parentWindow:null};this.hf=function(a,f){return-1<f.indexOf(a)};this.Ke=function(a){try{return a!=a.top&&a.parent&&this.Hb(a.parent)?a.parent:null}catch(f){return null}};this.Hb=function(a){try{return a&&a.document&&this.rd(a.document)?!0:!1}catch(f){return!1}};this.rd=function(a){try{return a&&a.getElementsByTagName&&a.getElementById?!0:!1}catch(f){return!1}};this.Mc=function(a,f){var d=f.parent,l={w:0,h:0,left:0,right:0,top:0,bottom:0};a&&(l=this.qc(a,f),l.w=l.right-l.left,l.h=l.bottom-l.top,
f!=d&&this.Yb(f,d)&&(d=this.Mc(f.frameElement,d),d.bottom<l.bottom&&(d.bottom<l.top&&(l.top=d.bottom),l.bottom=d.bottom),d.top>l.top&&(d.top>l.bottom&&(l.bottom=d.top),l.top=d.top),d.right<l.right&&(d.right<l.left&&(l.left=d.right),l.right=d.right),d.left>l.left&&(d.left>l.right&&(l.right=d.left),l.left=d.left),l.w=l.right-l.left,l.h=l.bottom-l.top));return l};this.ec=function(a,f){return function(){return a.apply(f,arguments)}};this.xa=function(a){try{return a?a.length?a.length:0:0}catch(f){return 0}};
this.tc=function(a){for(var f=[],d=0;d<a.length;d++)this.nf(a[d])&&f.push(a[d]);return f};this.a=function(a){try{maxLength=3,$dv&&($dv.Ra=$dv.Ra||[],$dv.Ra.push(a),$dv.Ra.length>maxLength&&$dv.Ra.shift())}catch(f){}};this.Ue=function(){try{return $dv&&$dv.Ra?$dv.Ra.join():""}catch(a){return""}};this.ya=function(a){if(a.$sf&&a.$sf.ext)if(a.$sf.ext.geom){if(a=this.Qa(a),null!=a&&a.win&&(0<a.win.h||0<a.win.w))return this.ya=function(){return!0},!0}else if(a.$sf.ext.inViewPercentage)return!0;this.ya=
function(){return!1};return!1};this.Qa=function(a){a.$sf.ext.geom&&(this.Qa="function"==typeof a.$sf.ext.geom?function(a){return a.$sf.ext.geom()}:function(a){return a.$sf.ext.geom});return this.Qa(a)};this.G=function(a,f){if(null!=a&&null!=f)for(var d in f)f.hasOwnProperty(d)&&(a[d]=f[d])};this.xc=function(a){return a.context&&a.context.observeIntersection?!0:!1};this.Fb=function(){var a=!1;if(1==this.cb("disableIO"))return!1;"undefined"!=typeof IntersectionObserver&&(a=!0);return a};this.Gb=function(a,
f,d){var l=d&&d.Enums.BrowserId||window.$dv.Enums.BrowserId;if(a==(d&&d.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario).CrossDomain&&(!(f.U!==l.Safari&&7!=f.U||null!==f.pa&&void 0!==f.pa&&/^[3-8]/.test(f.pa))||(6==f.U||f.U==l.Chrome)&&(null===f.pa||45<f.pa)))return this.Gb=function(){return!0},!0;this.Gb=function(){return!1};return!1};this.Ac=function(a,f,d){var l=d&&d.Enums.BrowserId||window.$dv.Enums.BrowserId,k=$dv.tags[$uid].AVO&&$dv.tags[$uid].AVO.fls;if(a==(d&&d.Enums.TrafficScenario||
window.$dv.Enums.TrafficScenario).CrossDomain&&f.U===l.IE&&k)return this.Ac=function(){return!0},!0;this.Ac=function(){return!1};return!1};this.cb=function(a){var f,d=this.ed();d&&d.AVO&&(f=d.AVO[a]);return f};this.ed=function(){var a={},f=window.$dv,d=window.$uid;f.tags&&f.tags[d]&&(a=f.tags[d]);return a};this.Qb=function(){return 1==this.cb("sam")?!0:!1};this.hb=function(a){return a.document.hasFocus()};this.yb=new function(){var a=this;a.cache=[];window.addEventListener?a.add=function(f,d,l,k,
u){if("undefined"==typeof k||null==k)k=window;k.addEventListener(f,d,l);u&&a.cache.push([f,d,l,k])}:window.attachEvent?a.add=function(f,d,l,k,u){if("undefined"==typeof k||null==k)k=window;k["e"+f+d]=d;k[f+d]=function(){k["e"+f+d](window.event)};k.attachEvent("on"+f,k[f+d]);u&&a.cache.push([f,d,l,k])}:a.add=function(){};window.removeEventListener?a.remove=function(a,d,l,k){if("undefined"==typeof k||null==k)k=window;k.removeEventListener(a,d,l)}:window.detachEvent?a.remove=function(a,d,l,k){if("undefined"==
typeof k||null==k)k=window;k.detachEvent("on"+a,k[a+d]);k[a+d]=null;k["e"+a+d]=null}:a.remove=function(){};a.flush=function(){for(var f=0;f<a.cache.length;f++)a.remove.apply(a,a.cache[f]);a.cache=[]}};this.getElementsByClassName=function(a,f){return a.getElementsByClassName?a.getElementsByClassName(f):a.querySelectorAll?a.querySelectorAll("."+f):[]};this.Da=function(){var a=!1;if($dv&&$dv.CommonData){var f=$dv.CommonData.detectedDeliveryType;f&&0!=f?a=2==f||3==f:(f=$dv.CommonData.deviceType)&&(a=
2==f||3==f)}return a};this.Te=function(a,f){var d=a||"",l="";if(f&&(d+=": "+(f.message||""),f.stack)){var l=f.stack||"",k=l.indexOf("at ");0>k&&(k=0);l=", Stack: "+l.slice(k,l.length)}d=d.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"");l=l.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"").replace(/    at/g,"at").replace(/\?/g,"-").replace(/&/g,"-");k=null;try{k=encodeURIComponent(d+l).slice(0,500)}catch(u){try{k=encodeURIComponent(d).slice(0,500)}catch(r){k=
d.slice(0,500)}}return k}}
function aa(a,f,d,l,k,u){function r(a){var c=[],b=null;a&&a.parentNode&&(b=a.parentNode.firstChild);for(;b;)1===b.nodeType&&b!==a&&c.push(b),b=b.nextElementSibling||b.nextSibling;return c}var q=new O;this.i=l;this.window=d;this.c=null;this.dataObj=a;this.dvObj=a.dvObj||window.$dv;this.wc=null;this.O={U:this.dvObj.CommonData.BrowserId,pa:this.dvObj.CommonData.BrowserVersion};this.da=this.dvObj.Enums.BrowserId;this.V=k;this.fa=this.dvObj.Enums.TrafficScenario;this.la=f;this.m=u.m;var g=0;115==this.dataObj.Oa&&
(this.m.J.h=20,this.m.J.w=20);this.Lf=function(){u.Ef(this.c);this.c=u.c=null};var m=[],w="object embed img iframe svg canvas".split(" ");this.dataObj.spotXmode&&(w=["object","embed","video","iframe"]);this.lf=function(a){q.a("a33");a=q.ia(a);var c=!1;return c=this.dataObj.Ec&&this.m.ha.h&&this.m.ha.w?this.bg(a,this.m.ha.w,this.m.ha.h):this.mf(a)};this.bg=function(a,c,b){var e=this.m.Ya||15;if(c&&b)return Math.abs(a.w-c)<=e&&Math.abs(a.h-b)<=e};this.mf=function(a){if(a){var c=a.w;a=a.h;for(var b=
this.m.Ya||15,e=f.length,p=0,n=0;n<e;n++)if(Math.abs(c-f[n].w)<=b)for(var p=f[n].h.length,g=0;g<p;g++)if(Math.abs(a-f[n].h[g])<=b)return!0}return!1};this.Oe=function(){q.a("a34");return this.Pe()||this.Of()};this.Of=function(){q.a("a35");var a=(window.name||(window.frameElement?window.frameElement.id:"")).substr(7),c=[],b=window.parent;q.a("ff6");try{c=b.document.getElementsByTagName("script")}catch(p){}q.a("ff6e");for(var b=c.length,e=0;e<b;e++)if(c[e]&&c[e].id&&c[e].id.substr(7)==a)return c[e];
return null};this.Pe=function(){q.a("a36");return this.dvObj&&this.dataObj.impressionId&&this.dvObj.tags&&this.dvObj.tags[this.dataObj.impressionId]?this.dvObj.tags[this.dataObj.impressionId].tagElement:null};this.oe=function(a){q.a("a38");var c={node:a,Ba:0};a=[];for(m=[];c||0<a.length;){try{var b;a:{var e=c.node;try{if(e&&-1!=w.indexOf(e.nodeName.toLowerCase())){b=!0;break a}}catch(g){}b=!1}if(b&&this.lf(c.node)&&!u.ra(c.node)&&u.T(c.node))return c;if(c.Ba<=this.m.vf){var p,n=c.node,d=c.Ba,c=[],
f=n.parentNode;f&&-1==m.indexOf(f)&&(m.push(f),c.push({node:f,Ba:d+1}));if(n.hasChildNodes())for(var k=0;k<n.childNodes.length;k++)n.childNodes[k]&&-1==m.indexOf(n.childNodes[k])&&1===n.childNodes[k].nodeType&&(m.push(n.childNodes[k]),c.push({node:n.childNodes[k],Ba:d+1}));for(var l=r(n),k=0;k<l.length;k++)l[k]&&-1==m.indexOf(l[k])&&1===l[k].nodeType&&(m.push(l[k]),c.push({node:l[k],Ba:d+1}));if(p=c)for(c=0;c<p.length;c++)a.push(p[c])}}catch(g){}c=a.shift()}return{node:null}};this.We=function(a){q.a("a37");
var c=null;a&&(c=this.oe(a));return c};this.Ne=function(a){a=r(a);g=1;for(var c=0;c<a.length;c++)if(a[c]&&-1==m.indexOf(a[c])&&1===a[c].nodeType&&u.yc(a[c])&&!u.ra(a[c])){var b=u.lc(a[c]);if(b){if(u.T(a[c]))return u.T(b),{node:b,Ba:1}}else g=4}};this.Fe=function(a){q.a("a31");if(this.c=u.Ve())return this.i.Td(),this.wc=!0,this.c;if(this.dataObj.btreg&&!0===this.wc&&1<a)return this.c;if("1"!=this.dataObj.displaynon){var c=this.Oe(),b;this.dataObj.Oa==u.$c&&(b=this.Ne(c));this.dataObj.Ec&&(g=3);!b&&
a>=g&&(b=this.We(c));b&&b.node&&(this.i.Sd(b.Ba),this.c=b.node)}return this.c};return this}
function ba(a,f,d,l,k,u){function r(c,b){for(var e=[],a=0;a<h.length;a++){var n=[],n=b(c,h[a]),g=m.xa(n);if(0!=g){var d=m.md(h[a]);if(null!=d)for(var f=0;f<g;f++)try{n[f].Cb=d,e.push(n[f])}catch(k){}}}return e}function q(c,b){return r(c,function(c,a){m.a("ff4");var g=a.getElementsByTagName(c);m.a("ff4e");return"1"!=b?g:m.tc(g)})}var g=this,m=new O,w="Microsoft Internet Explorer"==navigator.appName;this.dataObj=a;this.window=f;this.c=d;this.V=l;this.fa=k;this.dvObj=void 0===u?u={}:u;this.m={J:{h:1,
w:1},ha:{h:0,w:0},Ya:15,vf:10};this.$c="179";115==this.dataObj.Oa&&(this.m.J.h=20,this.m.J.w=20);this.dataObj.Ec&&this.dataObj.Hd&&this.dataObj.Gd&&(this.m.ha.h=this.dataObj.Gd,this.m.ha.w=this.dataObj.Hd);this.Ze=function(c){if(c.scanOrder)return c.scanOrder;var b=[1==w?"object":"embed",1==w?"embed":"object","href","img","span","iframe","frameElement","div","canvas","svg"];c.findclass&&1==c.findclass&&b.push("classDeclaration");c.ub&&0<c.ub.length&&b.unshift("searchCustomElementsFromTag");return b};
this.searchCustomElementsFromTag=function(c){for(var b=0;b<c.ub.length&&(g.bd(c.ub[b],c),!g.c);b++);};this.Sb=[["DCF",'"'],[";",";"],["%3B","%3B"],["zoneid=","_"],["zoneid%3D","_"],["PRImpID=",""],["PRImpID%3D",""],["PRPID=",""],["PRPID%3D",""]];this.xe=function(){var c=g.dataObj.xb+"-"+g.dataObj.wb;a.isBrandShieldOrigin&&(c+="-bs");return c.replace(RegExp(",","g"),";")};this.Ic=this.xe();this.bd=function(c,b){if(b.btreg)for(var e=q(c,b.displaynon),a=m.xa(e),n=0;n<a;n++)if(e[n]&&g.Ha(b,e[n],!0)&&
!g.ra(e[n])){var d=this.yc(e[n])?this.lc(e[n]):null;if(d&&(f=m.ia(d))&&f.h>g.m.J.h&&f.w>g.m.J.w&&g.T(d)){g.c=d;g.T(e[n]);break}var f=m.ia(e[n]);if(f&&f.h>g.m.J.h&&f.w>g.m.J.w&&g.T(e[n])){g.c=e[n];break}if((d=m.Tb(e[n],g.m.J.w,g.m.J.h,m.ec(m.ia,m),this.m.ha.w,this.m.ha.h,this.m.Ya))&&g.T(d)){g.c=d;g.T(e[n]);break}}};this.div=function(c){this.bd("div",c)};this.span=function(c){m.a("a10");if(c.btreg)for(var b=q("span",c.displaynon),e=m.xa(b),a=0;a<e;a++)if(b[a]&&g.Ha(c,b[a],!0)&&!g.ra(b[a])){var d=b[a];
m.a("a20");if(d&&"1"==d.getAttribute("adunit")){g.c=b[a];break}if(d=this.yc(b[a])?this.lc(b[a]):null){var f=m.ia(d);if(f&&f.h>g.m.J.h&&f.w>g.m.J.w&&g.T(d)){g.c=d;g.T(b[a]);break}}if((d=m.Tb(b[a],g.m.J.w,g.m.J.h,m.ec(m.ia,m),this.m.ha.w,this.m.ha.h,this.m.Ya))&&g.T(d)){g.c=d;g.T(b[a]);break}}};this.object=function(c){m.a("a11");for(var b=q("object",c.displaynon),a=m.xa(b),p=0;p<a;p++)if(b[p]&&g.Ha(c,b[p])&&!g.ra(b[p])){var d=m.Tb(b[p],g.m.J.w,g.m.J.h,m.ec(m.ia,m),this.m.ha.w,this.m.ha.h,this.m.Ya);
if(d&&g.T(d)){g.T(b[p]);g.c=d;break}}};this.rc=function(c,b){m.a("a14");for(var a=q(b,c.displaynon),p=m.xa(a),d=0;d<p;d++)if(a[d]&&g.Ha(c,a[d])&&!g.ra(a[d])){var f=m.ia(a[d]);if(f&&f.h>g.m.J.h&&f.w>g.m.J.w&&g.T(a[d])){g.c=a[d];break}}};this.embed=function(c){m.a("a12");this.rc(c,"embed")};this.href=function(c){m.a("a13");for(var b=q("a",c.displaynon),a=m.xa(b),d=0;d<a;d++)if(b[d]&&g.Ha(c,b[d])&&!g.ra(b[d])){var f=b[d].getElementsByTagName("img");if(0<f.length){var h=m.ia(f[0]);if(h&&h.h>g.m.J.h&&
h.w>g.m.J.w&&g.T(b[d])){g.c=f[0];break}}}};this.img=function(c){m.a("a31");this.rc(c,"img")};this.canvas=function(c){m.a("a32");this.rc(c,"canvas")};this.classDeclaration=function(c){m.a("a9");var b="undefined"!==typeof window.document.getElementsByClassName,a="undefined"!==typeof window.document.querySelectorAll;if(c.btreg){var d=[];if(b)d=g.getElementsByClassName(c.btreg,c.displaynon);else if(a)d=g.querySelectorAll(c.btreg,c.displaynon);else return;c=m.xa(d);for(b=0;b<c;b++)if(d[b]&&!g.ra(d[b])&&
(a=m.ia(d[b]))&&a.h>g.m.J.h&&a.w>g.m.J.w&&g.T(d[b])){g.c=d[b];break}}};this.iframe=function(a){m.a("a15");for(var b=q("iframe",a.displaynon),e=m.xa(b),d=0;d<e&&!g.Qc(a,b[d]);d++);};this.frameElement=function(a){try{m.a("a16"),l==k.SameDomain&&g.Qc(a,window.frameElement)}catch(b){}};this.getElementsByClassName=function(a,b){return r(a,function(a,c){m.a("ff1");var d=c.getElementsByClassName(a);m.a("ff1e");return"1"!=b?d:m.tc(d)})};this.querySelectorAll=function(a,b){return r(a,function(a,c){m.a("ff3");
var d=c.querySelectorAll("."+a);m.a("ff3e");return"1"!=b?d:m.tc(d)})};this.oa=function(a,b){m.a("a28");return!a||!b||5>b.length?!1:null!=(g.Nc?g.Nc(a,b):g.Ub(a,b))?!0:g.gc&&"function"===typeof g.gc?g.gc(a,b):!1};this.Ha=function(a,b,e){m.a("a22");var d=null;return a.btreg&&(g.Nc=1==a.pf?g.Zd:g.Ub,d=g.ee(a,b,e))||!g.c&&(d=g.fe(a,b))?!0:!1};this.je=function(a){m.a("a21");if(a&&!g.ra(a)){var b=m.ia(a);if(b&&b.h>g.m.J.h&&b.w>g.m.J.w&&g.T(a))return g.c=a,!0}return!1};this.Qc=function(a,b){m.a("a17");return g.Ha(a,
b)?g.je(b):!1};this.ra=function(a){m.a("a19");if(a&&(a=a.getAttribute("dvvisit"))){a=a.split(",");for(var b=0;b<a.length;b++)if(a[b]==g.Ic)return!0}return!1};this.T=function(a){m.a("a18");if(a&&0==g.ra(a))try{var b=a.getAttribute("dvvisit");b?a.setAttribute("dvvisit",b+","+g.Ic):(m.a("ff5"),b=window.document.createAttribute("dvvisit"),m.a("ff5e"),b.value=g.Ic,a.setAttributeNode(b));$dv.eventBus&&window&&$dv.eventBus.dispatchEvent(window,"adLocated",{adElement:a,timeStamp:(new Date).getTime()});return!0}catch(e){}return!1};
this.Ef=function(a){a&&a.hasAttribute&&a.hasAttribute("dvvisit")&&a.removeAttribute("dvvisit")};this.Zd=function(a,b){m.a("a29");var e;try{e=(new RegExp(b)).exec(a)}catch(d){e=g.Ub(a,b)}return e};this.Ub=function(a,b){m.a("a30");var e=null;-1!==a.indexOf(b)&&(e=a);return e};this.yc=function(a){return this.dataObj.Oa==this.$c&&0==a.className.indexOf("celtra-ad-v")?!0:!1};this.lc=function(a){var b=null;a.celtra&&1==a.celtra.loaded&&(b=a.celtra.viewabilityObservee);b&&(b.Cb=m.md(b.ownerDocument)||window);
return b};var h=[];this.ee=function(a,b,e){m.a("a23");var d;try{if(a.Yc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(d=g.oa(b.id,a.btreg))||(d=g.oa(b.src,a.btreg));d||(d=g.oa(b.href,a.btreg));d||(d=g.oa(b.getAttribute("flashvars"),a.btreg));d||(d=g.oa(b.name,a.btreg));!d&&a.findclass&&1==a.findclass&&(d=g.oa(b.getAttribute("class"),a.btreg));if(!d&&g.dataObj.Pa&&0<g.dataObj.Pa.length)for(var f=g.dataObj.Pa,h=0;h<f.length&&!(d=g.oa(b.getAttribute(f[h]),a.btreg));h++);d||e||(d=g.oa(b.innerHTML,
a.btreg));d&&!e&&(d=g.de(a,b));return d}catch(k){return d}};this.Ia=function(a,b){m.a("a25");if(!a)return!1;a=a.toLowerCase();for(var e=0;e<g.Sb.length;e++){var d;if(b.Tc&&(d=(g.Sb[e][0]+b.Tc).toLowerCase(),d=a.indexOf(d),-1<d)||b.Bd&&(d=(g.Sb[e][0]+b.Bd).toLowerCase(),d=a.indexOf(d),-1<d))return!0}return!1};this.fe=function(a,b){m.a("a24");var e;try{if(a.Yc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(e=g.Ia(b.id,a))||(e=g.Ia(b.src,a));e||(e=g.Ia(b.href,a));e||(e=g.Ia(b.jg,a));e||(e=g.Ia(b.name,
a));e||(e=g.Ia(b.innerHTML,a));if(!e&&g.dataObj.Pa&&0<g.dataObj.Pa.length)for(var d=g.dataObj.Pa,f=0;f<d.length&&!(e=g.oa(b.getAttribute(d[f]),a.btreg));f++);return e}catch(h){return e}};this.de=function(a,b){m.a("a26");return null==a.ab||""==a.ab?!1:g.oa(g.Yd(b),a.ab)};this.searchByAdSrvId_8=function(a,b){m.a("a1");var e=/[0-9]+-[0-9]+-[0-9]+-[0-9]+/.exec(a);return null!=e&&(e=e.toString(),e.replace(RegExp("-","g"),"")==b)?!0:!1};this.gc=this["searchByAdSrvId_"+(g.dataObj?g.dataObj.Oa||"":"")];this.Yd=
function(a){m.a("a27");if(a.outerHTML)return a.outerHTML;for(var b=a.attributes.length,e="",d=0;d<b;d++)e=e+a.attributes[d].nodeName+"="+a.attributes[d].nodeValue+" ";return e+a.innerHTML};this.Ve=function(){m.a("32");var a=[];void 0===u.tags&&(u.tags={});void 0===u.tags[$uid]&&(u.tags[$uid]={});void 0!==u.tags[$uid].spvi&&(a.push(u.tags[$uid].spvi),-1<a[0].scanOrder.indexOf(",")&&(a[0].scanOrder=a[0].scanOrder.split(",")));g.dataObj.scanOrder=this.Ze(g.dataObj);a.push(g.dataObj);var b=g.window,e=
0,f=[];try{do{f.push(b.document);for(var n=f,k=b.document.getElementsByTagName("iframe")||[],l=0;l<k.length&&25>l;l++){var q=null,q=m.Re(k[l]);void 0!==q&&null!==q&&0==m.hf(q,n)&&n.push(q)}b=m.Ke(b)}while(b&&10>++e)}catch(r){}h=f;for(b=0;b<a.length;b++)for(e=a[b],f=0;f<e.scanOrder.length;f++)if(void 0!=g[e.scanOrder[f]]&&(g[e.scanOrder[f]](e),g.c))return g.c;return d};return this}
function dv_CustomClientViewAssureService(a){function f(a){return{Kf:{adView:a.rq.av,gf:a.rq.ic,Rc:a.rq.adc,uf:a.rq.mla,xd:a.rq.ldav,focus:a.rq.fc,Sc:a.rq.as,ac:a.rq.exp},Jf:{zd:d(a.rp.mt),Df:d(a.rp.pt),wf:d(a.rp.mr),Cf:d(a.rp.pr),eventId:a.rp.eid,Xc:a.rp.bl}}}function d(a){return"string"==typeof a?Array(a):a}this.ne=dv_InViewService;this.ne(a);this.dvObj=a.dvObj||window.$dv;this.impressionId=a.impressionId||window.$uid;this.b=new O;this.qb=[];a=$dv.tags[$uid].dc||a.dc||[];var l=this.b.ed().bgm,k;
for(k in a)a.hasOwnProperty(k)&&this.qb.push(new window.mc.ye(f(a[k]),l));var u=this.Vb;this.Vb=function(a){a=u(a);for(var d=0;d<this.qb.length;d++)this.qb[d].Ae(a,this.ba.interval);return a};var r=this.Wa;this.Wa=function(a,d){var f={};r(a,d);if(1==this.hc){for(var k=0;k<this.qb.length;k++){var h=this.qb[k].yf(),c;for(c in h)h.hasOwnProperty(c)&&(f[c]=h[c])}$dv.registerEventCall($uid,f)}}}window.mc=window.mc||{};
window.mc.ye=function(a,f){function d(b){b.u&&b.u.f&&b.u.f.j&&b.u.f.o&&242500<=b.u.f.o*b.u.f.j&&(u=!0,l.xd&&(l.adView=l.xd),d=function(){})}var l=a.Kf,k=a.Jf,u=!1,r=!1,q=!1,g=!1,m=!1,w=!1,h=!1;l.ac&&$dv.registerEventCall($uid,{dvp_ex:0});this.Ae=function(b,a){d(b);var f=!0,k;k=l.focus?b.g:b.W;l.adView&&l.adView>k&&(f=!1);l.Sc&&b.u&&b.u.f&&b.u.f.j&&b.u.f.o&&b.u.f.o*b.u.f.j<l.Sc&&(f=!1);f?c+=a:l.gf&&(c=0);l.ac&&!r&&(!b.Ma&&98<=k&&($dv.registerEventCall($uid,{dvp_ex:1}),r=!0),b.Y&&(m=m||b.Y.pb,g=g||
b.Y.ob,h=h||b.Y.$a,w=w||b.Y.Za,m&&g&&h&&w&&(r=!0,$dv.registerEventCall($uid,{dvp_ex:2}))),b.Ma&&!b.Y&&(r=!0,$dv.registerEventCall($uid,{dvp_ex:3})));this.se(b)};var c=0;this.yf=function(){return this.Gf(k.zd,k.wf,k.Xc)};this.Ed=function(){this.Hf(k.zd,k.Df,k.Cf,k.Xc,k.eventId);this.Ed=function(){}};this.se=function(b){if(l.Rc&&c>=l.Rc||u&&l.uf)q=!0;!q||l.ac&&!r||this.Ed(b)};var b;this.Gf=function(a,c,d){var g={};if(f&&d)return g;if(a)for(b=$dv.tags[$uid].getTimeDiff(),d=0;d<a.length;d++)g[a[d]]=b;
if(c)for(d=0;d<c.length;d++)$dv.pubSub.publish(c[d],$uid),window&&$dv.pubSub.publish(c[d],window.$frmId);return g};this.Hf=function(a,c,d,g,h){if(!f||!g){if(c){g={};for(var k=$dv.tags[$uid].getTimeDiff(),l=0;l<c.length;l++)g[c[l]]=k;h&&(g.evid=h);if(a)for(l=0;l<a.length;l++)g[a[l]]=b||$dv.tags[$uid].getTimeDiff();$dv.registerEventCall($uid,g)}if(d)for(l=0;l<d.length;l++)$dv.pubSub.publish(d[l],$uid),window&&$dv.pubSub.publish(d[l],window.$frmId)}}};
function ca(){var a=!1,f=!1,d=0,l=0,k=!1;this.update=function(u,r,q,g){k||(r?(a=!0,0<q?(f=!0,q>=(u?30:50)?(l+=g,d+=g,1E3<=d&&(k=!0)):d=0):d=0):d=0)};this.Ye=function(){return k?6:a?f?0==l?3:1E3>l?4:1E3>d?5:6:2:1}}
function dv_InViewService(a){function f(){null===k.interval&&(k.interval=setInterval(k.Se(),k.ba.interval))}function d(){if(!1===k.ud){k.ud=!0;try{k.b.yb.remove("load",arguments.callee,!1,element)}catch(b){}k.Nb();k.b.a("s41");k.ua=new X(k.re?k.re:k.window,k.c,k.V,k.O,k.P,k.i.Zc,k.dvObj,k.impressionId);k.b.a("s42");k.ae();k.start()}}function l(b,a){return b.isReportingDisabled?new S:new R(b,a)}var k=this;this.yd=10;this.me=a.serverSettings&&a.serverSettings.jsVersion?a.serverSettings.jsVersion:"694";
this.dvObj=a.dvObj||window.$dv;this.impressionId=a.impressionId||window.$uid;this._minor_version="0";this.b=new O;this.df=function(){for(var b=document.getElementsByTagName("script"),a=b.length,c,d=0;d<a;d++)if(c=b[d].src,/visit[.]js/.test(c))return c.substring(c.indexOf("?")+1)};this.ud=!1;this.Ad=new ca;this.bf=function(){var b="";this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].tagElement&&(b=this.dvObj.tags[this.impressionId].tagElement.src,b=
b.substring(b.indexOf("?")+1));return b};this.ld=function(){return((new Date).getTime()+""+Math.floor(1E6*Math.random())).substr(0,16)};this.X=function(b,a){b=b.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=(new RegExp("[\\?&]"+b+"=([^&#]*)")).exec("?"+a);return c=c?c[1]:null};this.cf=function(){var b=this.X("uid",this.ea);null==b?(b=this.ld(),this.ea=this.ea+"&uid="+b):""==b&&(b=this.ld(),this.ea=this.ea.replace("&uid=","&uid="+b));return b};this.Gc=function(b,a,c,d){if(d&&d.insertBefore&&d.firstChild&&
(b=this.window.document.createElement(b))){for(var f in a)b[f]=a[f];for(f in c)b.style[f]=c[f];d.insertBefore(b,d.firstChild);return b}return null};this.qe=function(){var b=this.dvObj.Enums.TrafficScenario;try{if(window.top==window)return b.OnPage;if(window.top.document.domain==window.document.domain)return b.SameDomain}catch(a){}return b.CrossDomain};this.V=this.dvObj.CommonData.Scenario||this.qe();this.O={U:this.dvObj.CommonData.BrowserId,pa:this.dvObj.CommonData.BrowserVersion};this.da=this.dvObj.Enums.BrowserId;
this.fa=this.dvObj.Enums.TrafficScenario;this.lb="default";this.dataObj=a;this.window=a.tagWindow||parent.window||window;this.c=null;this.Kc=this.Xa=!1;this.Bc=!0;this.interval=null;this.ea=this.df();this.va=this.bf();a.serverSettings&&a.serverSettings.protocol&&a.serverSettings.protocol.indexOf("http");this.ba=window.Ce||this.window.Ce||{interval:100,Fa:{"default":{time:null,yb:["beforeunload","unload"],Od:84E4}}};this.Dd={};var u=null,r=1==this.b.cb("int");this.I=window.Be||this.window.Be||{interval:r?
100:1E3,Z:r?60:6};r=a&&a.Qd?a.Qd:!1;a=a&&a.Rd?a.Rd:!1;!1!==r&&!1!==a&&(this.I.interval=r,this.I.Z=a,$dv.registerEventCall(this.impressionId,{hg:this.I.interval,ig:this.I.Z}));this.I.interval=this.I.interval||1E3;this.I.Z=this.I.Z||6;this.I.Bf=this.I.Z;a=this.b.Da();this.ve={vb:12,kc:10,kb:30};this.P={Firefox:{ca:115},Chrome:{ca:89},Safari:{ca:38},Explorer:{ca:55},zf:500,Da:a,kb:30};var q=!1,g=0,m=[5,10,15];window.devicePixelRatio&&(this.P.Firefox.ca=0);this.dataObj.spotXmode=this.dataObj.videoEnable||
this.dataObj.detectVideoPlayer||this.dataObj.spotXmode;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].spotXmode&&(this.dataObj.spotXmode=this.dvObj.tags[this.impressionId].spotXmode);this.la=window.dv_configAdSize||this.window.dv_configAdSize||[{w:300,h:[90,100,200,250,268,600,618,850,1050,413,50,31]},{w:160,h:[600,800]},{w:120,h:[60,90,240,600,800,20]},{w:970,h:[66,90,250,30,415,550]},{w:728,h:[90,120]},{w:88,h:[31]},{w:700,h:[500]},{w:250,h:[60,
250,300,360,600]},{w:180,h:[150,160,600]},{w:234,h:[60]},{w:468,h:[60]},{w:550,h:[480]},{w:125,h:[125]},{w:336,h:[280,600,850]},{w:745,h:[90]},{w:954,h:[60]},{w:184,h:[90]},{w:800,h:[600]},{w:320,h:[360,50,100,480,320]},{w:1280,h:[100]},{w:640,h:[480,90,360]},{w:270,h:[460,202]},{w:613,h:[460]},{w:405,h:[303]},{w:950,h:[90]},{w:610,h:[100]},{w:272,h:[220]},{w:200,h:[200,446,90]},{w:220,h:[90]},{w:240,h:[133,400]},{w:960,h:[90]},{w:580,h:[400]},{w:750,h:[100,200,30]},{w:930,h:[180,600]},{w:980,h:[90,
120]},{w:900,h:[240]},{w:275,h:[300]},{w:600,h:[400]},{w:168,h:[28]},{w:216,h:[36]},{w:292,h:[30]},{w:1250,h:[155]},{w:375,h:[150]},{w:1140,h:[200]}];this.dataObj.spotXmode&&(this.la.push({w:320,h:[240]}),this.la.push({w:400,h:[300]}),this.la.push({w:450,h:[338]}),this.la.push({w:600,h:[800]}),this.la.push({w:640,h:[360]}),this.la.push({w:854,h:[480]}),this.la.push({w:500,h:[375]}));this.Bb=this.cf();this.jc=!1;this.Va=function(b,a){this.window.cd||(this.window.cd=[]);this.window.cd.push({caller:b,
kg:a})};this.startTime=(new Date).getTime();this.ke=4;this.Oc=0;this.uc=!0;this.logEvents={startMeasure:1,nonMeasurable:2,timeout:3,beforeunload:4,iabViewable:5,iabCustom:6,updateRTN:7,unload:8,errorlevel1:16,fg:17,interval:32};this.hc=!1;this.Pd=function(){this.b.a("ie16");if(this.window.dv_logObject){var b=this.i.Le();this.window.dv_logObject[this.Bb]=b}this.b.a("ie16e")};this.Pb=function(b){this.b.a("ie17");this.Pb=this.jc?function(b){this.i.Kd(b);this.Pd()}:function(b){this.i.Kd(b)};this.Pb(b)};
this.Jc=function(b,a){this.Jc=this.jc?function(b,a){this.i.Jd(b,a);this.Pd()}:function(b,a){this.i.Jd(b,a)};this.Jc(b,a)};this.Nb=function(){this.b.a("s4");this.c=this.bc.Fe(Math.abs(this.I.Z-this.I.Bf));!this.c&&this.V==this.fa.CrossDomain&&this.b.ya(this.window)&&(this.I.Z=0);if(this.c)this.Pf(),this.i.Ff(this.c),setTimeout(f,this.bc.wc?10:50);else if(0<this.I.Z)this.I.Z--,this.Qf(),setTimeout(this.Ge(),this.I.interval);else{try{this.V==this.fa.CrossDomain&&(this.b.vd(this.window,this.la)||this.b.ya(this.window))?
(this.c=this.b.Ca(this.window),this.i.Id()):this.V==this.fa.SameDomain&&this.b.vd(this.window,this.la)?(this.c=this.b.Ca(window.parent),this.i.Id(),this.ue()):this.I.Z=-1}catch(b){this.I.Z=-1}setTimeout(f,10)}this.b.a("s4e")};this.ue=function(){for(var b=this.window;b.parent!=b.top;)b=b.parent;this.b.a("ff26");for(var a=b.parent.document.getElementsByTagName("iframe"),c=a.length,d=0;d<c;d++)a[d].contentWindow==b&&(this.c=a[d],this.window=b.parent);this.b.a("ff26e")};this.Qf=function(){this.dataObj.btreg&&
this.dataObj.ab?this.i.Uf():this.i.Vf()};this.Pf=function(){this.b.a("s9");this.Xa=!0;this.i.Rf();this.b.a("s9e")};this.le=function(){this.dataObj.Oa=this.X("adsrv",this.ea)||"";this.dataObj.btreg=this.X("btreg",this.ea)||"";this.dataObj.Bd=this.X("plcid",this.ea)||"";"8"==this.dataObj.Oa&&""==this.dataObj.btreg&&(this.dataObj.btreg=this.dataObj.plcid);this.dataObj.ab=this.X("btadsrv",this.ea)||"";this.dataObj.Tc=this.X("adid",this.ea)||"";this.dataObj.Bb=this.Bb;this.dataObj.pf=this.X("isbtregex",
this.va)||"";this.dataObj.xb=this.X("ctx",this.ea)||"";this.dataObj.wb=this.X("cmp",this.ea)||"";this.dataObj.qf=this.X("lomd",this.va)||"";this.dataObj.findclass=this.X("findclass",this.va)||"";this.dataObj.displaynon=this.X("displaynon",this.va)||"";this.dataObj.Yc=this.X("bsdvview",this.va)||"";var b=this.X("bttag",this.va)||"";this.dataObj.ub=0<b.length?b.split("|"):[];b=this.X("btattb",this.va)||"";this.dataObj.Pa=0<b.length?b.split("|"):[];this.dataObj.Ec="1"==this.X("seltag",this.va)?!0:!1;
if(b=this.X("unit",this.va)||"")b=b.toLowerCase().split("x"),this.dataObj.Hd=b[0]&&!isNaN(b[0])?parseInt(b[0]):0,this.dataObj.Gd=b[1]&&!isNaN(b[1])?parseInt(b[1]):0};this.Cd=function(b){b=this.Jb(b);return 0<b.length?{tagServiceResult:b.join(",")}:{}};this.Jb=function(b){if(!this.dvObj)return[];for(var a=[],c=0;c<b.length;c++){var d=this.dvObj.pubSub.publish(b[c],this.impressionId)||null;null!=d&&a.push(d);window&&(d=this.dvObj.pubSub.publish(b[c],window.$frmId)||null,null!=d&&a.push(d))}return a};
this.Ud=function(){this.dataObj.serverSettings&&this.dataObj.serverSettings.TKH&&(this.ea+="&TKH="+this.dataObj.serverSettings.TKH)};this.ze=function(){Array.prototype.indexOf=function(b){if(null==this)throw new TypeError;var a=Object(this),c=a.length>>>0;if(0===c)return-1;var d=0;1<arguments.length&&(d=Number(arguments[1]),d!=d?d=0:0!=d&&Infinity!=d&&-Infinity!=d&&(d=(0<d||-1)*Math.floor(Math.abs(d))));if(d>=c)return-1;for(d=0<=d?d:Math.max(c-Math.abs(d),0);d<c;d++)if(d in a&&a[d]===b)return d;return-1}};
this.inViewManager=function(){try{Array.prototype.indexOf||this.ze();this.Ud();this.le();this.i=new F(this.me,this.ve,this.dataObj);this.ja=l(this.dataObj,this.i);this.dataObj.isRTNsDisabled&&(this.Jb=function(){return[]});this.jc=this.window.dv_logObject?!0:!1;this.Wf();this.pe=new ba(this.dataObj,this.window,this.c,this.V,this.fa,this.dvObj);this.bc=new aa(this.dataObj,this.la,this.window,this.i,this.V,this.pe);var b=window.parent;"589953"==this.dataObj.xb&&"587351"==this.dataObj.wb||"589953"==
this.dataObj.xb&&"616389"==this.dataObj.wb||"polite"==this.dataObj.qf?(setTimeout(d,15E3),this.b.yb.add("load",function(){setTimeout(d,1E3)},!1,b,!1)):d()}catch(a){var c=this;this.Ja(function(){c.Va("inViewManager",a);c.i.nb("inViewManager",a);c.ja.ga(c.logEvents.errorlevel1)},"inViewManager",a)}};this.rb=function(b){this.b.a("ie20");-6!=b.g&&(-3==b.g||-5!=b.g&&0>b.g&&-1==this.I.Z)&&(this.Lc(),this.rb=function(){})};this.Lc=function(){this.ja.ga(this.logEvents.nonMeasurable);this.Jb(["IABNotMeasuredImpression"]);
this.Lc=function(){}};this.Wa=function(b,a){b.b.a("ie21");if(0<=a.g||-5==a.g&&-1>=b.I.Z){if(b.dvObj&&b.impressionId){b.b.a("ie23");var c=b.Cd(["IABMeasuredImpression"]);b.b.a("ie24");b.ja.ga(b.logEvents.startMeasure,c)}else b.ja.ga(b.logEvents.startMeasure);b.hc=!0;b.Wa=function(){};b.rb=function(){}}b.b.a("ie22")};this.Pc=function(b){this.b.a("ie25");if(this.i.fd()||b&&!0===b)this.b.a("ie27"),this.dvObj&&this.impressionId?(this.b.a("ie28"),b=this.Cd(["IABViewableImpression"]),this.b.a("ie29"),this.ja.ga(this.logEvents.iabViewable,
b)):this.ja.ga(this.logEvents.iabViewable),q=!0,this.Pc=function(){};this.b.a("ie26")};this.we=function(b){if(q&&this.i.fd())for(g+=b,b=0;b<m.length;b++)null!=m[b]&&g>=1E3*m[b]&&(this.Jb(["IABAdViewable"+m[b]+"Seconds"]),m[b]=null);else g=0};var w="hidden",h=0;this.hasFocus=function(){vis=["hidden","webkitHidden","mozHidden","msHidden","oHidden"];for(var b in vis)if(vis[b]in document){w=vis[b];break}b=1==this.b.cb("fcs");var a=!1;try{this.b.hb(this.window),a=!0}catch(c){}var d=!1;try{this.b.hb(this.window.top),
d=!0}catch(c){}var f=null,f=b&&a&&this.O.U==this.da.IE?function(){var b=k.b.hb(k.window);k.V==k.fa.OnPage&&(b=b&&k.Bc);return b}:b&&d?function(){var b=!0,b=k.b.hb(k.window.top);k.V==k.fa.OnPage&&(b=b&&k.Bc);return b}:"undefined"!==typeof document[w]?function(){return!k.window.document[w]}:d?function(){return k.b.hb(k.window.top)}:function(){return!0};this.hasFocus=function(){try{return f()}catch(b){h++,5<=h&&(this.hasFocus=function(){return!0})}return!0};return this.hasFocus()};this.sc=function(b){var a=
b.ua.Qe();b.b.a("ie12");null==this.c||-3==a.g||b.hasFocus()||(a.g=0);b.b.a("ie13");u=a;b.Ad.update(a.H,b.hasFocus(),a.g,b.ba.interval);b.i.Yf(b.Ad.Ye());return a};var c;this.Vb=function(b){var a;try{$uid&&dvObj&&dvObj.tags[$uid]&&dvObj.tags[$uid].getTimeDiff&&(a=dvObj.tags[$uid].getTimeDiff())}catch(d){}b.ba.interval=a-c||100;c=a;b.b.a("ie1");a=b.c?b.c.Cb||b.window:b.window;b.ua.c=b.c;b.ua.window=a;b.b.a("ie2");a=b.sc(b);b.Xa&&(-1==a.g||-2==a.g)&&-1<=b.I.Z&&($dv.registerEventCall($uid,{dvp_rlad:$dv.tags[$uid].getTimeDiff()}),
$dv.registerEventCall($uid,{dvp_rlr:Math.abs(a.g)}),b.Fd(b),b.Nb());b.b.a("ie3");-5==a.g&&(b.I.Z--,b.i.Ld(),b.Ua||(b.Ua=function(a){a=b.ua.Eb(a);b.i.mb(a)}));b.b.a("ie4");b.Ua&&0<a.g&&(b.Ua(a),b.Ua=null);b.b.a("ie5");if(b.Xa&&!b.Kc){b.Kc=!0;var f=b.ua.Eb(a);b.i.mb(f)}-5==a.g&&-1<=b.I.Z&&($dv.registerEventCall($uid,{dvp_rlad:$dv.tags[$uid].getTimeDiff()}),$dv.registerEventCall($uid,{dvp_rlr:Math.abs(a.g)}),b.Fd(b),b.Nb(),a=b.sc(b),-5==a.g&&0<b.I.Z&&b.i.Mf());b.b.a("ie6");b.Jc(a,b.ba.interval);b.b.a("ie7");
b.Pb(a);b.b.a("ie8");b.i.Nd(a.aa);b.rb(a);b.b.a("ie9");b.Wa(b,a);b.b.a("ie10");b.Pc();b.b.a("ie11");b.we(b.ba.interval);b.b.a("ie12");return a};this.Fd=function(b){b.Xa=!1;b.c=null;b.bc.Lf();b.ua.ef()};this.Se=function(){this.b.a("s26");var b=this;return function(){try{b.Vb(b)}catch(a){b.Ja(function(){b.Oc<b.ke&&(b.Oc++,b.Va("getIntervalCallback",a),b.i.nb("getIntervalCallback",a),b.ja.ga(b.logEvents.errorlevel1))},"getIntervalCallback",a)}}};this.kd=function(b){var a=this;return function(){a.Ja(function(){a.ja.ga(a.logEvents[b])},
"getReportEventCallback")}};this.Ge=function(){var b=this;return function(){b.Ja(function(){b.Nb();b.c||b.i.Ob()},"getAdLocateCallback")}};this.gb=function(){var b=this;return function(a){try{a||(a=b.window.event),b.Bc="blur"==a.type||"focusout"==a.type?!1:!0}catch(c){b.Ja(function(){b.Va("getFocBluEventCallback",c);b.i.nb("getFocBluEventCallback",c);b.ja.ga(b.logEvents.errorlevel1)},"getFocBluEventCallback",c)}}};this.$d=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var b=
this;this.dvObj.tags[this.impressionId].getViewabilityData=function(){try{for(var a=b.i.Me().slice(0),c=0;c<a.length;c++)void 0===a[c]||null===a[c]?a[c]=0:isNaN(a[c])||(a[c]/=1E3);var d={};d.bucket_0=a[0];d.bucket_1_9=a[1];d.bucket_100=a[11];for(c=2;10>=c;c++)d["bucket_"+(10*(c-1)).toString()+"_"+(10*c-1).toString()]=a[c];return{buckets:d,isAdMeasureable:b.hc,totalPageTime:(b.i.pc()-b.i.af())/1E3,notApplicableTime:b.i.hd()/1E3}}catch(f){return{}}}}}catch(a){}};this.ae=function(){try{if(this.dvObj&&
this.impressionId&&this.dvObj.tags[this.impressionId]){var b=this.dvObj.tags[this.impressionId];b.VA||(b.VA={});b.VA.getVisibilityResult=function(){var b={};b.perc=u.g;0<=u.g&&u.u&&u.u.f&&(b.adWidth=u.u.f.o,b.adHeight=u.u.f.j);return b};b.VA.getAdElem=function(){return k.c}}}catch(a){}};this.$d();this.start=function(){this.b.a("s35");this.Af(this);var b;this.ba&&this.ba.Fa&&this.ba.Fa[this.lb]&&(b=this.ba.Fa[this.lb].yb);if(b)for(var a=b.length,c=0;c<a;c++)this.Dd[b[c]]=this.kd(b[c]),this.Na(this.window,
b[c],this.Dd[b[c]]);this.Zf();this.ba&&this.ba.Fa&&this.ba.Fa[this.lb]&&this.ba.Fa[this.lb].Od&&setTimeout(this.If(),this.ba.Fa[this.lb].Od)};this.If=function(){var b=this;return function(){b.kd("timeout")();clearInterval(b.interval);b.ja.ga=function(){}}};this.Af=function(b){try{var a=b.sc(b);-5==a.g&&(this.i.Ld(),this.Ua||(this.Ua=function(a){a=b.ua.Eb(a);b.i.mb(a)}));if(b.Xa)if(this.Kc=!0,-5!=a.g){var c=b.ua.Eb(a);b.i.mb(c)}else b.i.mb("true");b.i.Nd(a.aa);var d=b.ua.Ie(a,b.i.hd());b.i.Tf(d);b.i.Md(a.g);
b.Pb(a);b.rb(a);b.Wa(b,a)}catch(f){b.Ja(function(){b.Va("onStartReport",f);b.i.nb("onStartReport",f);b.ja.ga(b.logEvents.errorlevel1)},"onStartReport",f)}};this.Zf=function(){this.Na(this.window,"blur",this.gb());this.Na(this.window,"focus",this.gb());this.Na(this.window.document,"click",this.gb());this.Na(this.window.document,"mousedown",this.gb());this.Na(this.window.document,"mouseup",this.gb())};this.Na=function(){function b(a,c,d){b=a.addEventListener?function(b,a,c){b.addEventListener(a,c,!1)}:
a.attachEvent?function(b,a,c){b.attachEvent("on"+a,c)}:function(b,a,c){b["on"+a]=c};b(a,c,d)}return function(a,c,d){b(a,c,d)}}();this.stop=function(){};this.Wf=function(){this.b.a("ff24");this.V==this.fa.CrossDomain?this.b.ya(this.window)||this.b.xc(this.window)||this.b.Fb()||this.b.Gb(this.V,this.O,this.dvObj)||(this.O.U!=this.da.Firefox&&this.O.U!=this.da.IE?this.i.Xf():this.O.U==this.da.Firefox&&"undefined"===typeof this.window.mozInnerScreenX&&this.i.Hc()):window.document.body.getBoundingClientRect||
this.i.Hc();this.uc=this.i.Zc();this.b.a("ff24e")};this.Ja=function(b,a,c){try{b()}catch(d){try{0<this.yd&&(this.yd--,b=c||d,a=a||"unknown caller",this.Va(a,b),this.i.nb(a,b),this.ja.ga(k.logEvents.errorlevel1))}catch(f){}}};return this}
try{window.dv_InViewService=dv_InViewService;dv_InViewService.prototype.inViewManager=dv_InViewService.prototype.inViewManager;var ViewAssureBootstrapper=function(a){(new dv_CustomClientViewAssureService(a)).inViewManager()};if("function"===typeof window.IVCallback)IVCallback(ViewAssureBootstrapper);else for(var Y=[window.$dvbs,window.$dvbsr],Z=0;Z<Y.length;Z++){var dvObj=Y[Z];if(dvObj&&"object"===typeof dvObj&&"function"===typeof dvObj.getTagObjectByService){var tagObject=dvObj.getTagObjectByService("avs694");
if(tagObject){var serviceParams=tagObject.services.avs694;serviceParams&&serviceParams.params&&ViewAssureBootstrapper(serviceParams.params)}}}}catch(a){};
